---

- name: "Display all variables/facts known for a host"
  debug:
    var: hostvars[inventory_hostname].ansible_os_family 
    # verbosity: 4

- name: "Display all variables/facts known for a host"
  debug:
    var: hostvars[inventory_hostname].ansible_distribution

- name: "Display all variables/facts known for a host"
  debug:
    var: hostvars[inventory_hostname].ansible_distribution_major_version

- name: "Display all variables/facts known for a host"
  debug:
    var: hostvars[inventory_hostname].ansible_distribution_release

- name: "Display all variables/facts known for a host"
  debug:
    var: hostvars[inventory_hostname].ansible_distribution_version

- name: "Display all variables/facts known for a host"
  debug:
    var: hostvars[inventory_hostname] 
    verbosity: 3

- name: "Install {{ ansible_distribution }}-{{ ansible_distribution_version }}"
  include_tasks: "{{ ansible_distribution }}_{{ ansible_distribution_version }}_install.yml"

# - name: "OS fingerprinting "
#   debug:
#     msg: 
#     - "Provisioning based on YOUR_KEY which is: {{ lookup('env', 'YOUR_KEY') }}"

# - name: "OS fingerprinting "
#   debug:
#     msg: 
#       - "System {{ inventory_hostname }} has gateway {{ ansible_default_ipv4.gateway }}"

# - debug:
#     msg:
#     - "Provisioning based on YOUR_KEY which is: {{ lookup('env', 'YOUR_KEY') }}"
#     - "These servers were built using the password of '{{ password_used }}'. Please retain this for later use."

# - name: "OS fingerprinting "
#   debug:
#     msg:
#     - " ansible_os_family: {{ hostvars[inventory_hostname].ansible_os_family }} "

